// 최근 등록 10장. 앨범 아트가 붙기 전까지 color 로 개별화한다
export const NEW_VINYLS = [
  {
    id: 1,
    title: "Sunday Morning",
    artist: "The Lanes",
    year: 2025,
    genre: "Jazz-Ambient",
    color: "#c8553d",
  },
  {
    id: 2,
    title: "Paper Tides",
    artist: "Mira Oh",
    year: 2025,
    genre: "K-indie",
    color: "#e0a458",
  },
  {
    id: 3,
    title: "Slow Signal",
    artist: "Halden",
    year: 2024,
    genre: "Folk",
    color: "#7a9e7e",
  },
  {
    id: 4,
    title: "Blue Hour",
    artist: "Seo Jina",
    year: 2025,
    genre: "City Pop",
    color: "#2f5a72",
  },
  {
    id: 5,
    title: "Static Bloom",
    artist: "Verre",
    year: 2024,
    genre: "Rock",
    color: "#b5838d",
  },
  {
    id: 6,
    title: "Honey Circuit",
    artist: "Loop Kids",
    year: 2025,
    genre: "Pop",
    color: "#e9c46a",
  },
  {
    id: 7,
    title: "Dusk Ledger",
    artist: "Ilse Marr",
    year: 2023,
    genre: "Classical",
    color: "#6d597a",
  },
  {
    id: 8,
    title: "Second Story",
    artist: "Rowan Vale",
    year: 2025,
    genre: "R&B/Soul",
    color: "#3d5a80",
  },
  {
    id: 9,
    title: "Amber Tape",
    artist: "The Weekdays",
    year: 2024,
    genre: "Hip-hop",
    color: "#ee9b00",
  },
  {
    id: 10,
    title: "Glass Field",
    artist: "Nari",
    year: 2025,
    genre: "OST",
    color: "#8ecae6",
  },
];
